services:
  mongo:
    restart: always
    image: mongo:6.0.13-jammy
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGO_API_USER
      - MONGO_API_PWD
    volumes:
      - database:/data/db
      - ./mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

volumes:
  database:

  #mariadb:

  #app: #python

## Comandos desde mongosh
# test> use admin
# switched to db admin
# admin> db.auth("root","example")
# { ok: 1 }
# admin> use dbtest
# switched to db dbtest
# dbtest> show collections